//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int job_id { get; set; }
        public int cpy_id { get; set; }
        public string job_title { get; set; }
        public string job_desc { get; set; }
        public string location { get; set; }
        public string job_experience { get; set; }
        public string job_skill { get; set; }
        public string job_status { get; set; }
        public System.DateTime current_date { get; set; }
        public System.DateTime end_date { get; set; }
        public int pass_out_year { get; set; }
        public string job_qualification { get; set; }
    }
}
