//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class mvcprojectEntities1 : DbContext
    {
        public mvcprojectEntities1()
            : base("name=mvcprojectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<application> applications { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<userr> userrs { get; set; }
    
        public virtual ObjectResult<Nullable<int>> max_reg_id()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("max_reg_id");
        }
    
        public virtual int sp_application_insert(Nullable<int> user_id, Nullable<int> job_id, Nullable<System.DateTime> application_date, string resume)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var job_idParameter = job_id.HasValue ?
                new ObjectParameter("job_id", job_id) :
                new ObjectParameter("job_id", typeof(int));
    
            var application_dateParameter = application_date.HasValue ?
                new ObjectParameter("application_date", application_date) :
                new ObjectParameter("application_date", typeof(System.DateTime));
    
            var resumeParameter = resume != null ?
                new ObjectParameter("resume", resume) :
                new ObjectParameter("resume", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_application_insert", user_idParameter, job_idParameter, application_dateParameter, resumeParameter);
        }
    
        public virtual int sp_check_application(Nullable<int> uid, Nullable<int> job_id)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var job_idParameter = job_id.HasValue ?
                new ObjectParameter("job_id", job_id) :
                new ObjectParameter("job_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_check_application", uidParameter, job_idParameter);
        }
    
        public virtual int sp_comp_reg(Nullable<int> aid, string ana, string adesc, string aemail, string aaddr, string aphone)
        {
            var aidParameter = aid.HasValue ?
                new ObjectParameter("aid", aid) :
                new ObjectParameter("aid", typeof(int));
    
            var anaParameter = ana != null ?
                new ObjectParameter("ana", ana) :
                new ObjectParameter("ana", typeof(string));
    
            var adescParameter = adesc != null ?
                new ObjectParameter("adesc", adesc) :
                new ObjectParameter("adesc", typeof(string));
    
            var aemailParameter = aemail != null ?
                new ObjectParameter("aemail", aemail) :
                new ObjectParameter("aemail", typeof(string));
    
            var aaddrParameter = aaddr != null ?
                new ObjectParameter("aaddr", aaddr) :
                new ObjectParameter("aaddr", typeof(string));
    
            var aphoneParameter = aphone != null ?
                new ObjectParameter("aphone", aphone) :
                new ObjectParameter("aphone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_comp_reg", aidParameter, anaParameter, adescParameter, aemailParameter, aaddrParameter, aphoneParameter);
        }
    
        public virtual int sp_get_applied_jobs(Nullable<int> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_get_applied_jobs", uidParameter);
        }
    
        public virtual ObjectResult<sp_job_singleview_Result> sp_job_singleview(Nullable<int> job_id)
        {
            var job_idParameter = job_id.HasValue ?
                new ObjectParameter("job_id", job_id) :
                new ObjectParameter("job_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_job_singleview_Result>("sp_job_singleview", job_idParameter);
        }
    
        public virtual int sp_jobinsert(Nullable<int> cid, string jtitle, string jdesc, string jloc, string jexp, string jskill, Nullable<System.DateTime> cdate, Nullable<System.DateTime> edate, Nullable<int> pot, string jqua)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var jtitleParameter = jtitle != null ?
                new ObjectParameter("jtitle", jtitle) :
                new ObjectParameter("jtitle", typeof(string));
    
            var jdescParameter = jdesc != null ?
                new ObjectParameter("jdesc", jdesc) :
                new ObjectParameter("jdesc", typeof(string));
    
            var jlocParameter = jloc != null ?
                new ObjectParameter("jloc", jloc) :
                new ObjectParameter("jloc", typeof(string));
    
            var jexpParameter = jexp != null ?
                new ObjectParameter("jexp", jexp) :
                new ObjectParameter("jexp", typeof(string));
    
            var jskillParameter = jskill != null ?
                new ObjectParameter("jskill", jskill) :
                new ObjectParameter("jskill", typeof(string));
    
            var cdateParameter = cdate.HasValue ?
                new ObjectParameter("cdate", cdate) :
                new ObjectParameter("cdate", typeof(System.DateTime));
    
            var edateParameter = edate.HasValue ?
                new ObjectParameter("edate", edate) :
                new ObjectParameter("edate", typeof(System.DateTime));
    
            var potParameter = pot.HasValue ?
                new ObjectParameter("pot", pot) :
                new ObjectParameter("pot", typeof(int));
    
            var jquaParameter = jqua != null ?
                new ObjectParameter("jqua", jqua) :
                new ObjectParameter("jqua", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobinsert", cidParameter, jtitleParameter, jdescParameter, jlocParameter, jexpParameter, jskillParameter, cdateParameter, edateParameter, potParameter, jquaParameter);
        }
    
        public virtual int SP_Jobsearches(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Jobsearches", qryParameter);
        }
    
        public virtual ObjectResult<sp_jobview_Result> sp_jobview()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_jobview_Result>("sp_jobview");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_logincount_id(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_logincount_id", unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_logingetid(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_logingetid", unaParameter, pwdParameter);
        }
    
        public virtual int sp_logininsert(Nullable<int> rid, string una, string pw, string utype)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            var utypeParameter = utype != null ?
                new ObjectParameter("utype", utype) :
                new ObjectParameter("utype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_logininsert", ridParameter, unaParameter, pwParameter, utypeParameter);
        }
    
        public virtual ObjectResult<string> sp_logintype(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_logintype", unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<sp_selectall_Result> sp_selectall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectall_Result>("sp_selectall");
        }
    
        public virtual ObjectResult<sp_selectcompany_Result> sp_selectcompany()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectcompany_Result>("sp_selectcompany");
        }
    
        public virtual int sp_user_reg(Nullable<int> uid, string na, Nullable<int> ag, string addr, string ph, string sk, string eiy, string qua, string em, string ge)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var phParameter = ph != null ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(string));
    
            var skParameter = sk != null ?
                new ObjectParameter("sk", sk) :
                new ObjectParameter("sk", typeof(string));
    
            var eiyParameter = eiy != null ?
                new ObjectParameter("eiy", eiy) :
                new ObjectParameter("eiy", typeof(string));
    
            var quaParameter = qua != null ?
                new ObjectParameter("qua", qua) :
                new ObjectParameter("qua", typeof(string));
    
            var emParameter = em != null ?
                new ObjectParameter("em", em) :
                new ObjectParameter("em", typeof(string));
    
            var geParameter = ge != null ?
                new ObjectParameter("ge", ge) :
                new ObjectParameter("ge", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_user_reg", uidParameter, naParameter, agParameter, addrParameter, phParameter, skParameter, eiyParameter, quaParameter, emParameter, geParameter);
        }
    }
}
